import type { ModItem, ModPackage } from './types';
import type { RouteData } from '../../types/story';
import i18n from '../../i18n';
import { ModPackageSchema } from './schema';
import { GAME_CONSTANTS } from '../../utils/constants';

const { GITEE_OWNER, GITEE_REPO } = GAME_CONSTANTS.MOD_STORE;

/**
 * Fetch approved mods from static mods.json
 */
export const fetchApprovedMods = async (page = 1, perPage = 10): Promise<ModItem[]> => {
  // 请求�?CI/CD 或本地脚本预先生成的同源 mods.json，彻底解�?API 次数限制问题
  const url = `${import.meta.env.BASE_URL}mods.json`;
  
  try {
    const res = await fetch(url);
    if (!res.ok) {
      if (res.status === 404) {
        console.warn('mods.json not found. Please run `node scripts/sync-mods.mjs` locally or wait for CI.');
        return [];
      }
      throw new Error(`HTTP error! status: ${res.status}`);
    }
    
    const allMods: ModItem[] = await res.json();
    
    // 前端执行分页
    const start = (page - 1) * perPage;
    return allMods.slice(start, start + perPage);
  } catch (error) {
    console.error('Failed to fetch mods from static JSON:', error);
    return [];
  }
};

/**
 * Extract and validate Mod JSON from issue markdown body
 */
export const parseModPackage = (markdownBody: string): ModPackage => {
  if (!markdownBody) {
    throw new Error('Markdown body is empty.');
  }
  
  // 使用更宽松的正则来提取 JSON，适配不同的换行符（如 \r\n 或 \n）以及可能的空格干扰
  const match = markdownBody.match(/<!--\s*MOD_DATA_START\s*-->[\s\S]*?```json[\r\n]+([\s\S]*?)[\r\n]+```[\s\S]*?<!--\s*MOD_DATA_END\s*-->/i);
  
  if (!match || !match[1]) {
    // 作为一个兜底方案：如果找不到完整的标记，尝试仅通过 ```json 来匹配
    const fallbackMatch = markdownBody.match(/```json[\r\n]+([\s\S]*?)[\r\n]+```/i);
    if (!fallbackMatch || !fallbackMatch[1]) {
      throw new Error('No valid Mod JSON block found in the content.');
    }
    
    try {
      const rawJson = JSON.parse(fallbackMatch[1]);
      return ModPackageSchema.parse(rawJson);
    } catch (e) {
      throw new Error(`Fallback JSON parse failed: ${  (e as Error).message}`);
    }
  }

  try {
    const rawJson = JSON.parse(match[1]);
    return ModPackageSchema.parse(rawJson);
  } catch (e) {
    throw new Error(`JSON parse or validation failed: ${  (e as Error).message}`);
  }
};

/**
 * Generate Gitee New Issue URL for publishing
 */
export const generatePublishUrl = (manifest: Omit<ModItem, 'id' | 'createdAt' | 'contentBody' | 'tags' | 'avatarUrl'>, storyData: { routes: RouteData[] }) => {
  const title = encodeURIComponent(`[Mod] ${manifest.title}`);
  
  const packageData: ModPackage = {
    manifest: {
      id: '', // Generated by Gitee later as issue number
      title: manifest.title,
      author: manifest.author,
      description: manifest.description,
      version: '1.0.0'
    },
    storyData
  };

  const bodyStr = `
**${i18n.t('mods.publish.descLabel')}**：${manifest.description}

**${i18n.t('mods.publish.authorLabel')}**：${manifest.author}

> ${i18n.t('mods.publish.warning')}
<!-- MOD_DATA_START -->
\`\`\`json
${JSON.stringify(packageData, null, 2)}
\`\`\`
<!-- MOD_DATA_END -->
  `.trim();

  const body = encodeURIComponent(bodyStr);
  
  // 检查 URL 长度，保守取 1000 字符限制
  const fullUrl = `https://gitee.com/${GITEE_OWNER}/${GITEE_REPO}/issues/new?issue[title]=${title}&issue[description]=${body}`;
  if (fullUrl.length > 1000) {
    // 触发 fallback：只传标题，不传 description。然后将 JSON 拷贝到剪贴板，提示用户手动粘贴。
    return {
      url: `https://gitee.com/${GITEE_OWNER}/${GITEE_REPO}/issues/new?issue[title]=${title}`,
      clipboardData: bodyStr,
      isTooLong: true
    };
  }

  return {
    url: fullUrl,
    clipboardData: null,
    isTooLong: false
  };
};
